modLoader="kotlinforforge" #mandatory
loaderVersion="[5.3,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license = "MIT"

[[mods]]
modId = "veryscuffedcobblemonbreeding"
version = "${version}"
displayName = "Very Scuffed Cobblemon Breeding"
description = '''

'''

#[[mixins]]
#config = "mixins.cobblemon-neoforge.json"
[[mixins]]
config = "mixins.veryscuffedcobblemonbreeding-common.json"


[[dependencies.veryscuffedcobblemonbreeding]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21]"
ordering = "NONE"
side = "BOTH"

[[dependencies.veryscuffedcobblemonbreeding]]
modId = "neoforge"
mandatory = true
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.veryscuffedcobblemonbreeding]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.6.0,)"
ordering = "NONE"
side = "BOTH"
